'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';

const API_URL=(process.env.NEXT_PUBLIC_API_URL||'https://lalapay-api.vercel.app').replace(/\/$/,'');
const APP_URL=(process.env.NEXT_PUBLIC_APP_URL||'https://lalapay.vercel.app').replace(/\/$/,'');

type Link={id:string;title:string;amount:number;currency:string;status:string;paymentMethods:string[];createdAt:string;expiresAt?:string|null;description?:string|null};
type Tx={id:string;provider:string;amount:string|number;currency:string;status:string;provider_transaction_id?:string|null;provider_payment_id?:string|null;payment_link_id?:string;payment_link_title?:string;created_at:string;completed_at?:string|null;customer_name?:string|null;customer_email?:string|null;customer_phone?:string|null};
type Stats={total_links:number;active_links:number;total_transactions:number;successful_transactions:number;pending_transactions:number;failed_transactions:number;total_revenue:string|number;today_revenue:string|number;month_revenue:string|number};
type Pagination={limit:number;offset:number;total:number};
const labels:Record<string,string>={ACTIVE:'Active',INACTIVE:'Inactive',EXPIRED:'Expired',SUCCESS:'Success',PENDING:'Pending',FAILED:'Failed',INITIATED:'Initiated'};
const money=(n:unknown)=>`৳${Number(n||0).toLocaleString('en-BD',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dateLabel=(v?:string|null)=>v?new Date(v).toLocaleString():'';

export default function DashboardPage(){
 const router=useRouter();
 const[links,setLinks]=useState<Link[]>([]),[transactions,setTransactions]=useState<Tx[]>([]),[merchant,setMerchant]=useState<any>(null),[stats,setStats]=useState<Stats|null>(null);
 const[error,setError]=useState(''),[toast,setToast]=useState(''),[loading,setLoading]=useState(true),[creating,setCreating]=useState(false),[saving,setSaving]=useState(false);
 const[linkStatus,setLinkStatus]=useState('ALL'),[linkSearch,setLinkSearch]=useState(''),[txStatus,setTxStatus]=useState('ALL'),[txProvider,setTxProvider]=useState('ALL'),[txSearch,setTxSearch]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[txLink,setTxLink]=useState('ALL');
 const[pagination,setPagination]=useState<Pagination>({limit:20,offset:0,total:0}),[selected,setSelected]=useState<Tx|null>(null),[selectedLink,setSelectedLink]=useState<any|null>(null),[editing,setEditing]=useState<Link|null>(null);
 const[title,setTitle]=useState(''),[amount,setAmount]=useState(''),[description,setDescription]=useState(''),[expiresAt,setExpiresAt]=useState(''),[methods,setMethods]=useState<string[]>(['bkash','nagad']);
 const token=typeof window!=='undefined'?localStorage.getItem('lalapay_token'):null;
 const headers=useMemo(()=>token?{Authorization:`Bearer ${token}`,'Content-Type':'application/json'}:{'Content-Type':'application/json'},[token]);
 const load=useCallback(async(withSpinner=true,offset=0)=>{if(withSpinner)setLoading(true);setError('');if(!token){router.push('/login');return}try{
   const lq=new URLSearchParams({limit:'100',offset:'0'});if(linkSearch.trim())lq.set('search',linkSearch.trim());
   const tq=new URLSearchParams({limit:'20',offset:String(offset)});if(txStatus!=='ALL')tq.set('status',txStatus);if(txProvider!=='ALL')tq.set('provider',txProvider);if(txSearch.trim())tq.set('search',txSearch.trim());if(from)tq.set('from',new Date(from).toISOString());if(to)tq.set('to',new Date(to).toISOString());if(txLink!=='ALL')tq.set('paymentLinkId',txLink);
   const[me,lr,sr,tr]=await Promise.all([fetch(`${API_URL}/api/v1/auth/me`,{headers}),fetch(`${API_URL}/api/v1/payment-links?${lq}`,{headers}),fetch(`${API_URL}/api/v1/merchant/stats`,{headers}),fetch(`${API_URL}/api/v1/merchant/transactions?${tq}`,{headers})]);
   if([me,lr,sr,tr].some(r=>r.status===401)){localStorage.removeItem('lalapay_token');router.push('/login');return}
   const[m,l,s,t]=await Promise.all([me.json(),lr.json(),sr.json(),tr.json()]);
   if(!m.success)throw new Error(m.message||'Unable to load merchant.');if(!l.success)throw new Error(l.message||'Unable to load payment links.');if(!s.success)throw new Error(s.message||'Unable to load statistics.');if(!t.success)throw new Error(t.message||'Unable to load transactions.');
   setMerchant(m.data);setLinks(l.data||[]);setStats(s.data||null);setTransactions(t.data||[]);setPagination(t.pagination||{limit:20,offset,total:0});
 }catch(e){setError(e instanceof Error?e.message:'Unable to load dashboard.')}finally{if(withSpinner)setLoading(false)}},[headers,router,token,linkSearch,txStatus,txProvider,txSearch,from,to,txLink]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(t)},[toast]);
 async function createLink(e:FormEvent){e.preventDefault();setCreating(true);setError('');const n=Number(amount);if(!title.trim()||!Number.isFinite(n)||n<=0||Math.round(n*100)!==n*100){setError('Enter a valid title and amount.');setCreating(false);return}if(!methods.length){setError('Select at least one payment method.');setCreating(false);return}try{const r=await fetch(`${API_URL}/api/v1/payment-links`,{method:'POST',headers,body:JSON.stringify({title:title.trim(),amount:n,currency:'BDT',description:description.trim()||undefined,expiresAt:expiresAt?new Date(expiresAt).toISOString():undefined,paymentMethods:methods})}),b=await r.json();if(!r.ok||!b.success)throw new Error(b.message||'Could not create payment link.');setTitle('');setAmount('');setDescription('');setExpiresAt('');setMethods(['bkash','nagad']);setToast('Payment link created');await load(false)}catch(e){setError(e instanceof Error?e.message:'Could not create payment link.')}finally{setCreating(false)}}
 async function toggle(id:string,status:string){try{const r=await fetch(`${API_URL}/api/v1/merchant/payment-links/${id}/status`,{method:'PATCH',headers,body:JSON.stringify({status})}),b=await r.json();if(!r.ok||!b.success)throw new Error(b.message||'Could not update link.');setToast(status==='ACTIVE'?'Payment link activated':'Payment link deactivated');await load(false)}catch(e){setError(e instanceof Error?e.message:'Could not update link.')}}
 async function archiveLink(id:string){if(!window.confirm('Archive this payment link? Existing transaction records will remain safe.'))return;try{const r=await fetch(`${API_URL}/api/v1/merchant/payment-links/${id}`,{method:'DELETE',headers}),b=await r.json();if(!r.ok||!b.success)throw new Error(b.message||'Could not archive link.');setToast('Payment link archived');await load(false)}catch(e){setError(e instanceof Error?e.message:'Could not archive link.')}}
 async function duplicateLink(id:string){try{const r=await fetch(`${API_URL}/api/v1/merchant/payment-links/${id}/duplicate`,{method:'POST',headers}),b=await r.json();if(!r.ok||!b.success)throw new Error(b.message||'Could not duplicate link.');setToast('Payment link duplicated');await load(false)}catch(e){setError(e instanceof Error?e.message:'Could not duplicate link.')}}
 async function saveEdit(e:FormEvent){e.preventDefault();if(!editing)return;setSaving(true);try{const r=await fetch(`${API_URL}/api/v1/merchant/payment-links/${editing.id}`,{method:'PATCH',headers,body:JSON.stringify({title:editing.title,amount:Number(editing.amount),description:editing.description||undefined,expiresAt:editing.expiresAt||null,paymentMethods:editing.paymentMethods})}),b=await r.json();if(!r.ok||!b.success)throw new Error(b.message||'Could not update link.');setEditing(null);setToast('Payment link updated');await load(false)}catch(e){setError(e instanceof Error?e.message:'Could not update link.')}finally{setSaving(false)}}
 async function openLink(id:string){try{const r=await fetch(`${API_URL}/api/v1/merchant/payment-links/${id}`,{headers}),b=await r.json();if(!r.ok||!b.success)throw new Error(b.message||'Could not load payment link.');setSelectedLink(b.data)}catch(e){setError(e instanceof Error?e.message:'Could not load payment link.')}}
 function openTx(id:string){const tx=transactions.find(t=>t.id===id);if(tx)setSelected(tx);else setError('Transaction is no longer on this page. Refresh and try again.')}
 async function copy(id:string){try{await navigator.clipboard.writeText(`${APP_URL}/pay/${id}`);setToast('Payment link copied')}catch{setError('Copy failed.')}}
 function exportCsv(){const q=new URLSearchParams();if(txStatus!=='ALL')q.set('status',txStatus);if(txProvider!=='ALL')q.set('provider',txProvider);if(txSearch.trim())q.set('search',txSearch.trim());if(from)q.set('from',new Date(from).toISOString());if(to)q.set('to',new Date(to).toISOString());if(txLink!=='ALL')q.set('paymentLinkId',txLink);fetch(`${API_URL}/api/v1/merchant/transactions/export?${q}`,{headers:{Authorization:headers.Authorization||''}}).then(async r=>{if(!r.ok)throw new Error('CSV export failed');const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='lalapay-transactions.csv';a.click();URL.revokeObjectURL(url)}).catch(e=>setError(e instanceof Error?e.message:'CSV export failed'))}
 const filtered=links.filter(l=>linkStatus==='ALL'||l.status===linkStatus);const next=()=>pagination.offset+pagination.limit<pagination.total&&void load(true,pagination.offset+pagination.limit);const prev=()=>pagination.offset>0&&void load(true,Math.max(0,pagination.offset-pagination.limit));
 if(loading)return <main className="lp-page" style={{minHeight:'100vh',padding:24}}><div style={{maxWidth:1180,margin:'0 auto'}}><div className="lp-card" style={{height:28,width:130,marginBottom:16}}/><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:12}}>{Array.from({length:9},(_,i)=><div className="lp-card" key={i} style={{height:100}}/>)}</div></div></main>;
 return <main className="lp-page" style={{minHeight:'100vh',padding:'24px 16px'}}><div style={{maxWidth:1180,margin:'0 auto'}}>
 <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:14,marginBottom:22}}><div style={{display:'flex',alignItems:'center',gap:11}}><div style={{width:38,height:38,borderRadius:11,display:'grid',placeItems:'center',background:'linear-gradient(135deg,#7c3aed,#4f46e5)',color:'#fff',fontWeight:900}}>L</div><div><div style={{fontSize:20,fontWeight:900}}>LalaPay</div><div style={{fontSize:13,color:'#667085'}}>Merchant dashboard</div></div></div><button className="lp-btn secondary" onClick={()=>{localStorage.removeItem('lalapay_token');router.push('/login')}}>Sign out</button></header>
 {error&&<div role="alert" className="lp-card" style={{padding:13,marginBottom:16,color:'#b42318',background:'#fff1f1'}}>{error}<button onClick={()=>setError('')} style={{float:'right'}}>×</button></div>}{toast&&<div role="status" aria-live="polite" style={{position:'fixed',right:18,bottom:18,zIndex:40,padding:'13px 17px',borderRadius:12,background:'#101828',color:'#fff',boxShadow:'0 12px 30px rgba(0,0,0,.18)',fontWeight:700}}>{toast}</div>}
 <div style={{marginBottom:22}}><h1 style={{fontSize:30,letterSpacing:'-.04em',margin:'0 0 5px'}}>Good to see you, {merchant?.name||'Merchant'}</h1><p style={{margin:0,color:'#667085'}}>Create links, track payments, and manage your merchant activity.</p></div>
 <section style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:12,marginBottom:22}}>{[['Total Links',stats?.total_links??0],['Active Links',stats?.active_links??0],['Total Transactions',stats?.total_transactions??0],['Successful Payments',stats?.successful_transactions??0],['Pending Payments',stats?.pending_transactions??0],['Failed Payments',stats?.failed_transactions??0],['Total Revenue',money(stats?.total_revenue)],["Today's Revenue",money(stats?.today_revenue)],["This Month's Revenue",money(stats?.month_revenue)]].map(([a,b])=><div className="lp-card" key={String(a)} style={{padding:18}}><div style={{fontSize:12,color:'#667085'}}>{a}</div><strong style={{display:'block',fontSize:24,marginTop:6}}>{b}</strong></div>)}</section>
 <section className="lp-card" style={{padding:20,marginBottom:22}}><h2 style={{margin:'0 0 15px',fontSize:19}}>Create payment link</h2><form onSubmit={createLink} style={{display:'grid',gap:12}}><label>Title<input className="lp-input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Website development" required maxLength={150}/></label><label>Amount (BDT)<input className="lp-input" value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0.01" step="0.01" placeholder="1000.00" required/></label><label>Description <span style={{color:'#98a2b3'}}>(optional)</span><textarea className="lp-input" rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is this payment for?" maxLength={1000}/></label><label>Expiry <span style={{color:'#98a2b3'}}>(optional)</span><input className="lp-input" type="datetime-local" value={expiresAt} onChange={e=>setExpiresAt(e.target.value)}/></label><fieldset style={{border:'1px solid #eaecf0',borderRadius:12,padding:12}}><legend style={{padding:'0 5px',fontSize:13,fontWeight:800}}>Payment methods</legend><div style={{display:'flex',gap:20,flexWrap:'wrap'}}>{['bkash','nagad'].map(m=><label key={m} style={{display:'flex',gap:8,alignItems:'center',textTransform:'capitalize'}}><input type="checkbox" checked={methods.includes(m)} onChange={e=>setMethods(x=>e.target.checked?[...new Set([...x,m])]:x.filter(v=>v!==m))}/>{m}</label>)}</div></fieldset><button className="lp-btn" disabled={creating}>{creating?'Creating payment link…':'Create payment link'}</button></form></section>
 <section className="lp-card" style={{padding:20,marginBottom:22}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{margin:0,fontSize:19}}>Payment links</h2><p style={{margin:'4px 0 0',color:'#667085',fontSize:13}}>Search, edit, duplicate, archive, inspect statistics, or copy hosted URLs.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><input className="lp-input" style={{width:220}} value={linkSearch} onChange={e=>setLinkSearch(e.target.value)} placeholder="Search title or ID"/><select className="lp-input" style={{width:'auto'}} value={linkStatus} onChange={e=>setLinkStatus(e.target.value)}><option>ALL</option><option>ACTIVE</option><option>INACTIVE</option><option>EXPIRED</option></select></div></div>
 {!filtered.length?<Empty title={links.length?'No links match this filter':'No payment links yet'} text={links.length?'Try another search or filter.':'Create your first payment link above.'}/>:filtered.map(l=><article key={l.id} style={{borderTop:'1px solid #eaecf0',padding:'16px 0',display:'flex',justifyContent:'space-between',gap:14,flexWrap:'wrap'}}><button onClick={()=>void openLink(l.id)} style={{minWidth:0,border:0,background:'transparent',textAlign:'left',padding:0,cursor:'pointer'}}><strong>{l.title}</strong><div style={{marginTop:5,fontWeight:800}}>{money(l.amount)}</div><div style={{fontSize:12,color:'#667085',marginTop:4}}>{l.id} · {l.paymentMethods.join(' · ')} · {labels[l.status]||l.status}{l.expiresAt?` · ${new Date(l.expiresAt)<=new Date()?'Expired':'Expires'} ${dateLabel(l.expiresAt)}`:''}</div></button><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><button className="lp-btn secondary" onClick={()=>void copy(l.id)}>Copy</button><button className="lp-btn secondary" onClick={()=>setEditing({...l})}>Edit</button><button className="lp-btn secondary" onClick={()=>void duplicateLink(l.id)}>Duplicate</button>{l.status==='ACTIVE'?<button className="lp-btn secondary" onClick={()=>void toggle(l.id,'INACTIVE')}>Deactivate</button>:l.status!=='EXPIRED'&&<button className="lp-btn" onClick={()=>void toggle(l.id,'ACTIVE')}>Activate</button>}<button className="lp-btn secondary" onClick={()=>void archiveLink(l.id)}>Archive</button></div></article>)}</section>
 <section className="lp-card" style={{padding:20}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{margin:0,fontSize:19}}>Transactions</h2><p style={{margin:'4px 0 0',color:'#667085'}}>Search and filter payment activity with true server-side pagination.</p></div><button className="lp-btn secondary" onClick={exportCsv}>Export CSV</button></div><div style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr',gap:8,marginTop:14}}><input className="lp-input" value={txSearch} onChange={e=>setTxSearch(e.target.value)} placeholder="Search transaction, provider ID, link title or ID"/><select className="lp-input" value={txStatus} onChange={e=>setTxStatus(e.target.value)}><option>ALL</option><option>INITIATED</option><option>PENDING</option><option>SUCCESS</option><option>FAILED</option></select><select className="lp-input" value={txProvider} onChange={e=>setTxProvider(e.target.value)}><option>ALL</option><option value="bkash">bKash</option><option value="nagad">Nagad</option></select><select className="lp-input" value={txLink} onChange={e=>setTxLink(e.target.value)}><option value="ALL">All links</option>{links.map(l=><option key={l.id} value={l.id}>{l.title}</option>)}</select></div><div style={{display:'flex',gap:8,marginTop:8,flexWrap:'wrap'}}><label style={{fontSize:12,color:'#667085'}}>From<input className="lp-input" type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label style={{fontSize:12,color:'#667085'}}>To<input className="lp-input" type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="lp-btn" style={{alignSelf:'end'}} onClick={()=>void load(true,0)}>Apply filters</button></div>
 {!transactions.length?<Empty title="No transactions found" text="Try changing the filters."/>:transactions.map(t=><button key={t.id} onClick={()=>openTx(t.id)} style={{display:'block',width:'100%',padding:'15px 2px',border:0,borderTop:'1px solid #eaecf0',background:'transparent',textAlign:'left',cursor:'pointer'}}><strong>{money(t.amount)}</strong><span style={{marginLeft:8,textTransform:'capitalize'}}>{t.provider}</span><span style={{float:'right',fontWeight:800}}>{labels[t.status]||t.status}</span><small style={{display:'block',color:'#667085',marginTop:4}}>{t.payment_link_title||t.payment_link_id} · {dateLabel(t.created_at)}</small></button>)}
 <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,marginTop:15}}><button className="lp-btn secondary" disabled={!pagination.offset} onClick={prev}>Previous</button><span style={{fontSize:12,color:'#667085'}}>{pagination.total?`${pagination.offset+1}–${Math.min(pagination.offset+pagination.limit,pagination.total)} of ${pagination.total}`:'0 transactions'}</span><button className="lp-btn secondary" disabled={pagination.offset+pagination.limit>=pagination.total} onClick={next}>Next</button></div></section>
 {selectedLink&&<Modal title="Payment link details" close={()=>setSelectedLink(null)}><div style={{display:'grid',gap:10}}><strong>{selectedLink.link.title}</strong><span>{money(selectedLink.link.amount)} · {selectedLink.link.status}</span><span style={{color:'#667085'}}>ID: {selectedLink.link.id}</span><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:10}}>{[['Total payments',selectedLink.statistics.total_payments],['Successful',selectedLink.statistics.successful_payments],['Pending',selectedLink.statistics.pending_payments],['Failed',selectedLink.statistics.failed_payments],['Total collected',money(selectedLink.statistics.total_collected)]].map(([a,b])=><div className="lp-card" style={{padding:12}} key={String(a)}><small style={{color:'#667085'}}>{a}</small><strong style={{display:'block',marginTop:4}}>{b}</strong></div>)}</div><h3 style={{marginBottom:0}}>Recent payments</h3>{selectedLink.transactions?.slice(0,10).map((t:Tx)=><div key={t.id} style={{padding:'8px 0',borderTop:'1px solid #eaecf0'}}>{money(t.amount)} · {t.provider} · {labels[t.status]||t.status}</div>)}</div></Modal>}
 {selected&&<Modal title="Transaction details" close={()=>setSelected(null)}><dl style={{display:'grid',gridTemplateColumns:'145px 1fr',gap:10,fontSize:14}}>{[['Reference',selected.id],['Provider',selected.provider],['Status',labels[selected.status]||selected.status],['Amount',money(selected.amount)],['Payment link',selected.payment_link_title||selected.payment_link_id],['Provider payment ID',selected.provider_payment_id||'—'],['Provider transaction ID',selected.provider_transaction_id||'—'],['Created',dateLabel(selected.created_at)],['Completed',dateLabel(selected.completed_at)]].map(([a,b])=><div key={String(a)} style={{display:'contents'}}><dt style={{color:'#667085'}}>{a}</dt><dd style={{margin:0,wordBreak:'break-word'}}>{b}</dd></div>)}</dl></Modal>}
 {editing&&<Modal title="Edit payment link" close={()=>setEditing(null)}><form onSubmit={saveEdit} style={{display:'grid',gap:12}}><label>Title<input className="lp-input" value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} required/></label><label>Amount<input className="lp-input" type="number" step="0.01" value={editing.amount} onChange={e=>setEditing({...editing,amount:Number(e.target.value)})} required/></label><label>Description<textarea className="lp-input" value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>Expiry<input className="lp-input" type="datetime-local" value={editing.expiresAt?new Date(editing.expiresAt).toISOString().slice(0,16):''} onChange={e=>setEditing({...editing,expiresAt:e.target.value?new Date(e.target.value).toISOString():null})}/></label><fieldset><legend>Payment methods</legend><div style={{display:'flex',gap:18}}>{['bkash','nagad'].map(m=><label key={m}><input type="checkbox" checked={editing.paymentMethods.includes(m)} onChange={e=>setEditing({...editing,paymentMethods:e.target.checked?[...new Set([...editing.paymentMethods,m])]:editing.paymentMethods.filter(x=>x!==m)})}/> {m}</label>)}</div></fieldset><button className="lp-btn" disabled={saving}>{saving?'Saving…':'Save changes'}</button></form></Modal>}
 </div></main>
}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div role="dialog" aria-modal="true" onClick={close} style={{position:'fixed',inset:0,zIndex:30,background:'rgba(16,24,40,.48)',display:'grid',placeItems:'center',padding:16}}><section className="lp-card" onClick={e=>e.stopPropagation()} style={{width:'100%',maxWidth:620,maxHeight:'90vh',overflow:'auto',padding:24}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><h2 style={{marginTop:0}}>{title}</h2><button className="lp-btn secondary" onClick={close}>Close</button></div>{children}</section></div>}
function Empty({title,text}:{title:string;text:string}){return <div style={{textAlign:'center',padding:'42px 16px',color:'#667085'}}><div style={{fontSize:30,marginBottom:8}}>◌</div><strong style={{display:'block',color:'#101828'}}>{title}</strong><span style={{fontSize:13}}>{text}</span></div>}
